{
 "title": "Linkerd Multicluster",
 "tags": [ "linkerd" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(request_total, dst_target_cluster)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"height:32px;\"/>&nbsp;\n  <span style=\"font-size: 32px\">Cluster: $cluster</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", direction=\"outbound\"}[$__rate_interval])) / sum(irate(response_total{dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", direction=\"outbound\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(request_total{dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", direction=\"outbound\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", direction=\"outbound\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>TOP-LINE TRAFFIC</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\",dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", direction=\"outbound\"}[$__rate_interval])) / sum(irate(response_total{dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", direction=\"outbound\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", direction=\"outbound\", tls=\"true\"}[$__rate_interval]))"
    },
    {
     "expr": "sum(irate(request_total{dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", tls!=\"true\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", direction=\"outbound\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50 gateway"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", direction=\"outbound\"}[$__rate_interval])) by (le))",
     "legendFormat": "p95 gateway"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", direction=\"outbound\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99 gateway"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>TRAFFIC BY TARGET SERVICE</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", direction=\"outbound\"}[$__rate_interval])) by (dst_target_service) / sum(irate(response_total{dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", direction=\"outbound\"}[$__rate_interval])) by (dst_target_service)",
     "legendFormat": "target-svc/{{dst_target_service}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", tls=\"true\"}[$__rate_interval])) by (dst_target_service)",
     "legendFormat": "?target-svc/{{dst_target_service}}"
    },
    {
     "expr": "sum(irate(request_total{dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", tls!=\"true\"}[$__rate_interval])) by (dst_target_service)",
     "legendFormat": "target-svc/{{dst_target_service}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{dst_target_cluster=\"$cluster\", dst_target_cluster!=\"\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_target_service))",
     "legendFormat": "P95 target-svc/{{dst_target_service}}"
    }
   ]
  }
 ]
}
{
 "title": "Linkerd Health",
 "tags": [ "linkerd" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(process_start_time_seconds{namespace=~\"$namespace|$namespace-viz\"}, deployment)"
   },
   { "name": "component", "label": "Component", "query": "label_values(component)" },
   {
    "name": "namespace",
    "label": "Linkerd Namespace",
    "query": "label_values(process_start_time_seconds{control_plane_ns!=\"\"},  control_plane_ns)"
   },
   {
    "name": "namespace-viz",
    "label": "Linkerd Viz Namespace",
    "query": "label_values(process_start_time_seconds{control_plane_ns!=\"\",extension!=\"\"},  namespace)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>Data-Plane Telemetry</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "MEMORY USAGE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"linkerd-proxy\"}",
     "legendFormat": "{{namespace}}/{{pod}}/virtual"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"linkerd-proxy\"}",
     "legendFormat": "{{namespace}}/{{pod}}/resident"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=\"linkerd-proxy\"}[$__rate_interval])) by (namespace, pod)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "OPEN FILE DESCRIPTORS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"linkerd-proxy\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>Control-Plane Traffic</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", deployment!=\"\", namespace=~\"$namespace|$namespace-viz\", direction=\"inbound\"}[$__rate_interval])) by (pod) / sum(irate(response_total{deployment!=\"\", namespace=~\"$namespace|$namespace-viz\", direction=\"inbound\"}[$__rate_interval])) by (pod)",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{deployment!=\"\", namespace=~\"$namespace|$namespace-viz\", direction=\"inbound\"}[$__rate_interval])) by (pod)",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{deployment!=\"\", namespace=~\"$namespace|$namespace-viz\", direction=\"inbound\"}[$__rate_interval])) by (le, pod))",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>Control-Plane TCP Metrics</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "$deployment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "deployment",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
     "content": "<div>\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"baseline; height:40px;\"/>&nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$deployment</span>\n</div>"
    },
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{deployment=\"$deployment\", namespace=~\"$namespace|$namespace-viz\", direction=\"inbound\",errno!=\"\"}",
       "legendFormat": "{{peer}} {{errno}}"
      }
     ]
    },
    {
     "title": "OPEN TCP CONNECTIONS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{deployment=\"$deployment\", namespace=~\"$namespace|$namespace-viz\", direction=\"inbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{deployment=\"$deployment\", namespace=~\"$namespace|$namespace-viz\", direction=\"inbound\"}"
      }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>Control-Plane Telemetry</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"linkerd-controller\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"linkerd-controller\"}",
     "legendFormat": "{{component}}/resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"linkerd-controller\"}",
     "legendFormat": "{{component}}/virtual"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"linkerd-controller\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"linkerd-controller\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>Control-Plane Clients/Servers</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_total{job=\"linkerd-controller\"}[$__rate_interval])) by (component, method, code)",
     "legendFormat": "{{component}}/{{method}}/{{code}}"
    }
   ]
  },
  {
   "title": "HTTP Server Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_request_latency_seconds_bucket{job=\"linkerd-controller\"}[$__rate_interval])) by (le, component, method, code))",
     "legendFormat": "P50 {{component}}/{{method}}/{{code}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_latency_seconds_bucket{job=\"linkerd-controller\"}[$__rate_interval])) by (le, component, method, code))",
     "legendFormat": "P95 {{component}}/{{method}}/{{code}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_latency_seconds_bucket{job=\"linkerd-controller\"}[$__rate_interval])) by (le, component, method, code))",
     "legendFormat": "P99 {{component}}/{{method}}/{{code}}"
    }
   ]
  },
  {
   "title": "HTTP Server Response Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_response_size_bytes_bucket{job=\"linkerd-controller\"}[$__rate_interval])) by (le, component, method, code))",
     "legendFormat": "P50 {{component}}/{{method}}/{{code}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_response_size_bytes_bucket{job=\"linkerd-controller\"}[$__rate_interval])) by (le, component, method, code))",
     "legendFormat": "P95 {{component}}/{{method}}/{{code}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_response_size_bytes_bucket{job=\"linkerd-controller\"}[$__rate_interval])) by (le, component, method, code))",
     "legendFormat": "P99 {{component}}/{{method}}/{{code}}"
    }
   ]
  },
  {
   "title": "Client Request Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_client_requests_total{job=\"linkerd-controller\"}[$__rate_interval])) by (component, client, method, code)",
     "legendFormat": "{{component}}/{{client}}/{{method}}/{{code}}"
    }
   ]
  },
  {
   "title": "HTTP Client Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_client_request_latency_seconds_bucket{job=\"linkerd-controller\"}[$__rate_interval])) by (le, component, client, method, code))",
     "legendFormat": "P50 {{component}}/{{client}}/{{method}}/{{code}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_request_latency_seconds_bucket{job=\"linkerd-controller\"}[$__rate_interval])) by (le, component, client, method, code))",
     "legendFormat": "P95 {{component}}/{{client}}/{{method}}/{{code}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_client_request_latency_seconds_bucket{job=\"linkerd-controller\"}[$__rate_interval])) by (le, component, client, method, code))",
     "legendFormat": "P99 {{component}}/{{client}}/{{method}}/{{code}}"
    }
   ]
  },
  {
   "title": "Client In-Flight Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_client_in_flight_requests{job=\"linkerd-controller\"}) by (component, client)",
     "legendFormat": "{{component}}/{{client}}"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "repeat": "component",
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 59 },
   "content": "<div>\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"baseline; height:40px;\"/>&nbsp;\n  <span style=\"font-size: 15px; border-image:none\">$component</span>\n</div>",
   "targets": [
    {}
   ]
  },
  {
   "title": "Go Memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "alloc/{{component}}"
    },
    {
     "expr": "irate(go_memstats_alloc_bytes_total{job=\"linkerd-controller\", component=\"$component\"}[$__rate_interval])",
     "legendFormat": "alloc rate/{{component}}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "stack/{{component}}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"linkerd-controller\", component=\"$component\"}",
     "legendFormat": "heap/{{component}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"0.5\", component=\"$component\"}",
     "legendFormat": "P50 {{component}}"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"0.75\", component=\"$component\"}",
     "legendFormat": "P75 {{component}}"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"linkerd-controller\", quantile=\"1\", component=\"$component\"}",
     "legendFormat": "Max {{component}}"
    }
   ]
  },
  {
   "title": "gRPC Message Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "irate(grpc_server_msg_sent_total{job=\"linkerd-controller\", component=\"$component\"}[$__rate_interval])",
     "legendFormat": "sent/{{component}}/{{grpc_method}}"
    },
    {
     "expr": "irate(grpc_server_msg_received_total{job=\"linkerd-controller\", component=\"$component\"}[$__rate_interval])",
     "legendFormat": "received/{{component}}/{{grpc_method}}"
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 159 },
   "content": "<div>\n  <div style=\"position: absolute; top: 0, left: 0\">\n    <a href=\"https://linkerd.io\" target=\"_blank\"><img src=\"https://linkerd.io/images/identity/svg/linkerd_primary_color_white.svg\" style=\"height: 30px;\"></a>\n  </div>\n  <div id=\"version\" style=\"position: absolute; top: 0; right: 0; font-size: 15px\">\n  </div>\n</div>\n<div style=\"display:none\">\n<script type=\"text/javascript\">\nvar localReqURL =\n  window.location.href.substring(\n    0,\n    window.location.href.indexOf(\n    \"/grafana/\"\n    )\n  )+'/overview';\n\nfetch(localReqURL, {\n  credentials: 'include',\n  headers: {\n    \"Content-Type\": \"text/html; charset=utf-8\",\n  },\n})\n.then(response => response.text())\n.then(text => (new window.DOMParser()).parseFromString(text, \"text/html\"))\n.then(html => {\n  var main = html.getElementById('main');\n  var localVersion = main.getAttribute(\"data-release-version\");\n  var versionElem = document.getElementById('version');\n\n  var channel;\n  var parts = localVersion.split(\"-\", 2);\n  if (parts.length === 2) {\n    channel = parts[0];\n    versionElem.innerHTML += 'Running Linkerd ' + parts[1] + ' (' + parts[0] + ')' + '.<br>';\n  } else {\n    versionElem.innerHTML += 'Running Linkerd ' + localVersion + '.<br>';\n  }\n  var uuid = main.getAttribute(\"data-uuid\");\n\n  fetch('https://versioncheck.linkerd.io/version.json?version='+localVersion+'&uuid='+uuid+'&source=grafana', {\n    credentials: 'include',\n    headers: {\n      \"Content-Type\": \"application/json; charset=utf-8\",\n    },\n  })\n  .then(response => response.json())\n  .then(json => {\n    if (!channel || !json[channel]) {\n      versionElem.innerHTML += 'Version check failed.'\n    } else if (json[channel] === localVersion) {\n      versionElem.innerHTML += 'Linkerd is up to date.';\n    } else {\n      parts = json[channel].split(\"-\", 2);\n      if (parts.length === 2) {\n        versionElem.innerHTML += \"A new \"+parts[0]+\" version (\"+parts[1]+\") is available.\"\n      } else {\n        versionElem.innerHTML += \"A new version (\"+json[channel]+\") is available.\"\n      }\n      versionElem.innerHTML += \" <a href='https://versioncheck.linkerd.io/update' target='_blank'>Update now</a>.\";\n    }\n  });\n});\n</script>\n</div>",
   "targets": [
    {}
   ]
  }
 ]
}
{
 "title": "Linkerd Deployment",
 "tags": [ "linkerd" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(process_start_time_seconds{deployment!=\"\"}, namespace)"
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(process_start_time_seconds{namespace=\"$namespace\"}, deployment)"
   },
   {
    "name": "inbound",
    "query": "label_values(request_total{dst_namespace=\"$namespace\", dst_deployment=\"$deployment\"}, deployment)"
   },
   {
    "name": "outbound",
    "query": "label_values(request_total{namespace=\"$namespace\", deployment=\"$deployment\"}, dst_deployment)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"height:32px;\"/>&nbsp;\n  <span style=\"font-size: 32px\">deploy/$deployment</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "INBOUND DEPLOYMENTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(request_total{dst_namespace=\"$namespace\", deployment!=\"\", dst_deployment!=\"\", dst_deployment=\"$deployment\", direction=\"outbound\"}) by (namespace, deployment))"
    }
   ]
  },
  {
   "title": "OUTBOUND DEPLOYMENTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}) by (namespace, dst_deployment))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND TRAFFIC</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls=\"true\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "?deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\", tls!=\"true\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (le, deployment))",
     "legendFormat": "p50 deploy/{{deployment}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (le, deployment))",
     "legendFormat": "p95 deploy/{{deployment}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}[$__rate_interval])) by (le, deployment))",
     "legendFormat": "p99 deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "Inbound TCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\",errno!=\"\"}",
       "legendFormat": "{{peer}} {{errno}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTIONS OPEN",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"inbound\"}"
      }
     ]
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND DEPLOYMENTS</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "deploy/$inbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "inbound",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22.2 },
     "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"baseline; height:30px;\"/>&nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$inbound</span>\n</div>"
    },
    {
     "title": "SUCCESS RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24.2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(response_total{classification=\"success\", deployment!=\"\", deployment=\"$inbound\", dst_namespace=\"$namespace\", dst_deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (deployment, pod) / sum(irate(response_total{deployment!=\"\", deployment=\"$inbound\", dst_namespace=\"$namespace\", dst_deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (deployment, pod)",
       "legendFormat": "po/{{pod}}"
      }
     ]
    },
    {
     "title": "REQUEST RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24.2 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(request_total{deployment!=\"\", deployment=\"$inbound\", dst_namespace=\"$namespace\", dst_deployment=\"$deployment\", direction=\"outbound\", tls=\"true\"}[$__rate_interval])) by (deployment, pod)",
       "legendFormat": "?po/{{pod}}"
      },
      {
       "expr": "sum(irate(request_total{deployment!=\"\", deployment=\"$inbound\", dst_namespace=\"$namespace\", dst_deployment=\"$deployment\", direction=\"outbound\", tls!=\"true\"}[$__rate_interval])) by (deployment, pod)",
       "legendFormat": "po/{{pod}}"
      }
     ]
    },
    {
     "title": "LATENCY",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24.2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{deployment!=\"\", deployment=\"$inbound\", dst_namespace=\"$namespace\", dst_deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (le, deployment))",
       "legendFormat": "P50 deploy/{{deployment}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{deployment!=\"\", deployment=\"$inbound\", dst_namespace=\"$namespace\", dst_deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (le, deployment))",
       "legendFormat": "P95 deploy/{{deployment}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{deployment!=\"\", deployment=\"$inbound\", dst_namespace=\"$namespace\", dst_deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (le, deployment))",
       "legendFormat": "P99 deploy/{{deployment}}"
      }
     ]
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>OUTBOUND TRAFFIC</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (dst_deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (dst_deployment)",
     "legendFormat": "deploy/{{dst_deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\", tls=\"true\"}[$__rate_interval])) by (dst_deployment)",
     "legendFormat": "?deploy/{{dst_deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\", tls!=\"true\"}[$__rate_interval])) by (dst_deployment)",
     "legendFormat": "deploy/{{dst_deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_deployment))",
     "legendFormat": "P95 deploy/{{dst_deployment}}"
    }
   ]
  },
  {
   "title": "Outbound TCP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TCP CONNECTION FAILURES",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "tcp_close_total{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\",errno!=\"\"}",
       "legendFormat": "{{peer}} {{errno}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTIONS OPEN",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tcp_open_connections{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}",
       "legendFormat": "{{peer}}"
      }
     ]
    },
    {
     "title": "TCP CONNECTION DURATION",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "targets": [
      {
       "expr": "tcp_connection_duration_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", direction=\"outbound\"}"
      }
     ]
    }
   ]
  },
  {
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>OUTBOUND DEPLOYMENTS</span>\n</div>",
   "targets": [
    {}
   ]
  },
  {
   "title": "deploy/$outbound",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "outbound",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 },
     "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"baseline; height:30px;\"/>&nbsp;\n  <span style=\"font-size: 15px; border-image:none\">deploy/$outbound</span>\n</div>"
    },
    {
     "title": "SUCCESS RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval])) by (dst_deployment) / sum(irate(response_total{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval])) by (dst_deployment)",
       "legendFormat": "deploy/{{dst_deployment}}"
      }
     ]
    },
    {
     "title": "REQUEST RATE",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\", tls=\"true\"}[$__rate_interval])) by (dst_deployment)",
       "legendFormat": "?deploy/{{dst_deployment}}"
      },
      {
       "expr": "sum(irate(request_total{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\", tls!=\"true\"}[$__rate_interval])) by (dst_deployment)",
       "legendFormat": "deploy/{{dst_deployment}}"
      }
     ]
    },
    {
     "title": "LATENCY",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_deployment))",
       "legendFormat": "P50 deploy/{{dst_deployment}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_deployment))",
       "legendFormat": "P95 deploy/{{dst_deployment}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", deployment=\"$deployment\", dst_deployment=\"$outbound\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_deployment))",
       "legendFormat": "P99 deploy/{{dst_deployment}}"
      }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "content": "<div>\n  <div style=\"position: absolute; top: 0, left: 0\">\n    <a href=\"https://linkerd.io\" target=\"_blank\"><img src=\"https://linkerd.io/images/identity/svg/linkerd_primary_color_white.svg\" style=\"height: 30px;\"></a>\n  </div>\n  <div id=\"version\" style=\"position: absolute; top: 0; right: 0; font-size: 15px\">\n  </div>\n</div>\n<div style=\"display:none\">\n<script type=\"text/javascript\">\nvar localReqURL =\n  window.location.href.substring(\n    0,\n    window.location.href.indexOf(\n    \"/grafana/\"\n    )\n  )+'/overview';\n\nfetch(localReqURL, {\n  credentials: 'include',\n  headers: {\n    \"Content-Type\": \"text/html; charset=utf-8\",\n  },\n})\n.then(response => response.text())\n.then(text => (new window.DOMParser()).parseFromString(text, \"text/html\"))\n.then(html => {\n  var main = html.getElementById('main');\n  var localVersion = main.getAttribute(\"data-release-version\");\n  var versionElem = document.getElementById('version');\n\n  var channel;\n  var parts = localVersion.split(\"-\", 2);\n  if (parts.length === 2) {\n    channel = parts[0];\n    versionElem.innerHTML += 'Running Linkerd ' + parts[1] + ' (' + parts[0] + ')' + '.<br>';\n  } else {\n    versionElem.innerHTML += 'Running Linkerd ' + localVersion + '.<br>';\n  }\n  var uuid = main.getAttribute(\"data-uuid\");\n\n  fetch('https://versioncheck.linkerd.io/version.json?version='+localVersion+'&uuid='+uuid+'&source=grafana', {\n    credentials: 'include',\n    headers: {\n      \"Content-Type\": \"application/json; charset=utf-8\",\n    },\n  })\n  .then(response => response.json())\n  .then(json => {\n    if (!channel || !json[channel]) {\n      versionElem.innerHTML += 'Version check failed.'\n    } else if (json[channel] === localVersion) {\n      versionElem.innerHTML += 'Linkerd is up to date.';\n    } else {\n      parts = json[channel].split(\"-\", 2);\n      if (parts.length === 2) {\n        versionElem.innerHTML += \"A new \"+parts[0]+\" version (\"+parts[1]+\") is available.\"\n      } else {\n        versionElem.innerHTML += \"A new version (\"+json[channel]+\") is available.\"\n      }\n      versionElem.innerHTML += \" <a href='https://versioncheck.linkerd.io/update' target='_blank'>Update now</a>.\";\n    }\n  });\n});\n</script>\n</div>",
   "targets": [
    {}
   ]
  }
 ]
}
{
 "title": "Linkerd Authority",
 "tags": [ "linkerd" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(request_total, namespace)"
   },
   {
    "name": "authority",
    "label": "Authority",
    "query": "label_values(request_total{namespace=\"$namespace\"}, authority)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center\">\n  <img src=\"https://linkerd.io/images/identity/favicon/linkerd-favicon.png\" style=\"height:32px;\"/>&nbsp;\n  <span style=\"font-size: 32px\">au/$authority</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval])) / sum(irate(response_total{namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval])) by (le, authority))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>TOP-LINE TRAFFIC</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval])) by (authority) / sum(irate(response_total{namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval])) by (authority)",
     "legendFormat": "au/{{authority}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\", tls=\"true\"}[$__rate_interval])) by (authority)",
     "legendFormat": "?au/{{authority}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\", tls!=\"true\"}[$__rate_interval])) by (authority)",
     "legendFormat": "au/{{authority}}"
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval])) by (le, authority))",
     "legendFormat": "p50 au/{{authority}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval])) by (le, authority))",
     "legendFormat": "p95 au/{{authority}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", authority=\"$authority\", direction=\"inbound\"}[$__rate_interval])) by (le, authority))",
     "legendFormat": "p99 au/{{authority}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND TRAFFIC BY DEPLOYMENT</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\"}[$__rate_interval])) by (deployment) / sum(irate(response_total{namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\", tls=\"true\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "?deploy/{{deployment}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\", tls!=\"true\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "deploy/{{deployment}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\"}[$__rate_interval])) by (le, deployment))",
     "legendFormat": "P95 deploy/{{deployment}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>INBOUND TRAFFIC BY POD</span>\n</div>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "SUCCESS RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\"}[$__rate_interval])) by (pod) / sum(irate(response_total{namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\"}[$__rate_interval])) by (pod)",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "title": "REQUEST RATE",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\", tls=\"true\"}[$__rate_interval])) by (pod)",
     "legendFormat": "?po/{{pod}}"
    },
    {
     "expr": "sum(irate(request_total{namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\", tls!=\"true\"}[$__rate_interval])) by (pod)",
     "legendFormat": "po/{{pod}}"
    }
   ]
  },
  {
   "title": "P95 LATENCY",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", authority=\"$authority\", direction=\"outbound\"}[$__rate_interval])) by (le, pod))",
     "legendFormat": "P95 po/{{pod}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 33 },
   "options": {
    "content": "<div>\n  <div style=\"position: absolute; top: 0, left: 0\">\n    <a href=\"https://linkerd.io\" target=\"_blank\"><img src=\"https://linkerd.io/images/identity/svg/linkerd_primary_color_white.svg\" style=\"height: 30px;\"></a>\n  </div>\n  <div id=\"version\" style=\"position: absolute; top: 0; right: 0; font-size: 15px\">\n  </div>\n</div>\n<div style=\"display:none\">\n<script type=\"text/javascript\">\nvar localReqURL =\n  window.location.href.substring(\n    0,\n    window.location.href.indexOf(\n    \"/grafana/\"\n    )\n  )+'/overview';\n\nfetch(localReqURL, {\n  credentials: 'include',\n  headers: {\n    \"Content-Type\": \"text/html; charset=utf-8\",\n  },\n})\n.then(response => response.text())\n.then(text => (new window.DOMParser()).parseFromString(text, \"text/html\"))\n.then(html => {\n  var main = html.getElementById('main');\n  var localVersion = main.getAttribute(\"data-release-version\");\n  var versionElem = document.getElementById('version');\n\n  var channel;\n  var parts = localVersion.split(\"-\", 2);\n  if (parts.length === 2) {\n    channel = parts[0];\n    versionElem.innerHTML += 'Running Linkerd ' + parts[1] + ' (' + parts[0] + ')' + '.<br>';\n  } else {\n    versionElem.innerHTML += 'Running Linkerd ' + localVersion + '.<br>';\n  }\n  var uuid = main.getAttribute(\"data-uuid\");\n\n  fetch('https://versioncheck.linkerd.io/version.json?version='+localVersion+'&uuid='+uuid+'&source=grafana', {\n    credentials: 'include',\n    headers: {\n      \"Content-Type\": \"application/json; charset=utf-8\",\n    },\n  })\n  .then(response => response.json())\n  .then(json => {\n    if (!channel || !json[channel]) {\n      versionElem.innerHTML += 'Version check failed.'\n    } else if (json[channel] === localVersion) {\n      versionElem.innerHTML += 'Linkerd is up to date.';\n    } else {\n      parts = json[channel].split(\"-\", 2);\n      if (parts.length === 2) {\n        versionElem.innerHTML += \"A new \"+parts[0]+\" version (\"+parts[1]+\") is available.\"\n      } else {\n        versionElem.innerHTML += \"A new version (\"+json[channel]+\") is available.\"\n      }\n      versionElem.innerHTML += \" <a href='https://versioncheck.linkerd.io/update' target='_blank'>Update now</a>.\";\n    }\n  });\n});\n</script>\n</div>"
   },
   "targets": [
    {}
   ]
  }
 ]
}